### ISSUE TITLE
Swift 4.2 errors

### ISSUE THREAD

**Issue by flowbe** [abdullahselek/ASMapLauncher#1]
There is an error on the repo in Swift 4.2 so I cannot build my app… Can you look at it?
Here is the error:

    Type `UIApplication` does not conform to protocol `UIApplicationProtocol`

Thanks !

**Comment by abdullahselek** [comment]
Hi @TheFlow95 thanks for letting me know the issue. Please try new version `1.0.7`. If you get any error just let me know.

**Comment by flowbe** [comment]
This works just great! Thank you very much!
